spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myproject?charset=utf8mb4&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/myproject
      #username:
      #password:

  redis:
    host: 127.0.0.1
    port: 6379
    #passwoed: 