server:
    port: 9000
    
spring:
    profiles:
        active: common,dev
    application:
        name: login

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/