server:
  port: 9010
    
spring:
  profiles:
    active: dev
  application:
    name: face-recognition

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

context:
  initializer:
    classes: com.myproject.config.OpencvInitializer