server:
  port: 8089
    
spring:
  profiles:
    active: log
    #active: native
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/rainstarmoon/myproject
          searchPaths: base/src/main/resources
          username: 
          password:
      
      #server:
        #native:
          #search-locations: classpath:/config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/