server:
    port: 8099
    
spring:
    profiles:
        active: dev
    application:
        name: service-ribbon

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/